version: "2"

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - modernize
    - revive
    - misspell
    - unconvert
    - unparam
    - nilerr

formatters:
  enable:
    - gofumpt
    - goimports
    - golines
  settings:
    gofumpt:
      extra-rules: true
    goimports:
      local-prefixes: github.com/Crystalix007/net/logflt
    golines:
      max-len: 8
      tab-len: 2

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
  exclude-dirs: []
